### ISSUE TITLE
Failing with No LoginModules configured for KrbLogin

### ISSUE THREAD

**Issue by sprasad09** [srotya/storm-collectd#1]
Hello!

I have installed and setup the plugin config as such. When i start collectd, i get the error below. Please help! 

```
<Plugin java>
        JVMArg "-verbose:jni"
        JVMArg "-Djava.class.path=/usr/share/collectd/java/collectd-api.jar:/usr/share/collectd/storm-collectd/target/storm-collectd-0.0.1-SNAPSHOT-jar-with-dependencies.jar"

        LoadPlugin "com.srotya.collectd.storm.StormNimbusMetrics"

  <Plugin "storm">
        address "http://localhost:8080/"
        kerberos false
  </Plugin>
</Plugin>
```

[Dynamic-linking native method java.lang.Throwable.getStackTraceElement ... JNI]
	at javax.security.auth.login.LoginContext.init(LoginContext.java:264)
	at javax.security.auth.login.LoginContext.<init>(LoginContext.java:348)
	at com.srotya.collectd.storm.StormNimbusMetrics.login(StormNimbusMetrics.java:284)
	at com.srotya.collectd.storm.StormNimbusMetrics.read(StormNimbusMetrics.java:98)

javax.security.auth.login.LoginException: No LoginModules configured for KrbLogin
	at javax.security.auth.login.LoginContext.init(LoginContext.java:264)
	at javax.security.auth.login.LoginContext.<init>(LoginContext.java:348)
	at com.srotya.collectd.storm.StormNimbusMetrics.login(StormNimbusMetrics.java:284)
	at com.srotya.collectd.storm.StormNimbusMetrics.read(StormNimbusMetrics.java:98)
javax.security.auth.login.LoginException: No LoginModules configured for KrbLogin
	at javax.security.auth.login.LoginContext.init(LoginContext.java:264)
	at javax.security.auth.login.LoginContext.<init>(LoginContext.java:348)
	at com.srotya.collectd.storm.StormNimbusMetrics.login(StormNimbusMetrics.java:284)
	at com.srotya.collectd.storm.StormNimbusMetrics.read(StormNimbusMetrics.java:98)

**Comment by sprasad09** [comment]
I am not using kerberos so i have set it as false
